services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  mongodb:
    container_name: mongodb
    hostname: mongo
    image: mongo:7
    ports:
      - 27017:27017
    env_file:
      - .env.development
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ADMIN_PWD
      - MONGO_INITDB_DATABASE=$DATABASE_NAME
      - MONGO_INITDB_USERNAME=$DATABASE_USER
      - MONGO_INITDB_PASSWORD=$DATABASE_USER_PWD
    volumes:
      - ./apps/mongo/addons/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo_turbo_data:/data/db
    restart: unless-stopped
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  mongo_turbo_data:
