services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  postgres:
    container_name: postgres
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - postgres_turbo_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  postgres_turbo_data:
